[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "Eazure"
version = "0.1"
dependencies = [
    "azure-storage-blob>=12.8.1",
    "azure-core>=1.29.5",
    "azure-data-tables>=12.4.4",
    "azure-storage-blob>=12.18.3",
    "azure-storage-queue>=12.7.3"
]